platform="web";
			

/**
 * @constructor
 */
var NetgearStrings = function() {
		
	var strings = {
		"option_power_batterystate-NoBattery"     : "No Battery",
		"string_battery_remaining"                : "${percent}% remaining",
		"string_battery_complete"                 : "Charging; ${percent}% complete",
		"option_router_usbnetworktethering-true"  : "+1 via USB",
		"option_router_usbnetworktethering-false" : "no USB connections",
		"string_sim_pin_required"				  : "SIM PIN required",
		"string_sim_blocked"					  : "...you need an ${companyName}% SIM",
		'string_sim_not_present'				  : "No SIM installed...",
		'string_roaming'						  : "Roaming on ${companyName}%",
		'MESSAGE_FORMAT_DATE'					  : "%m/%d/%y",					  					
		'MESSAGE_FORMAT_DATE_TODAY'				  : "MESSAGE_FORMAT_DATE_TODAY",
		'MESSAGE_FORMAT_DATE_YESTERDAY'           : "MESSAGE_FORMAT_DATE_YESTERDAY",
		'MESSAGE_FORMAT_DATE_DAYS_AGO'            : "MESSAGE_FORMAT_DATE_DAYS_AGO",
		'MESSAGE_FORMAT_DATE_AT'				  : "MESSAGE_FORMAT_DATE_AT",
		'MESSAGE_FORMAT_DATE_JANUARY'			  : "MESSAGE_FORMAT_DATE_JANUARY",
		'MESSAGE_FORMAT_DATE_FEBRUARY'			  : "MESSAGE_FORMAT_DATE_FEBRUARY",
		'MESSAGE_FORMAT_DATE_MARCH'				  : "MESSAGE_FORMAT_DATE_MARCH",
		'MESSAGE_FORMAT_DATE_APRIL'				  : "MESSAGE_FORMAT_DATE_APRIL",
		'MESSAGE_FORMAT_DATE_MAY'			  	  : "MESSAGE_FORMAT_DATE_MAY",
		'MESSAGE_FORMAT_DATE_JUNE'			      : "MESSAGE_FORMAT_DATE_JUNE",
		'MESSAGE_FORMAT_DATE_JULY'			      : "MESSAGE_FORMAT_DATE_JULY",
		'MESSAGE_FORMAT_DATE_AUGUST'			  : "MESSAGE_FORMAT_DATE_AUGUST",
		'MESSAGE_FORMAT_DATE_SEPTEMBER'			  : "MESSAGE_FORMAT_DATE_SEPTEMBER",
		'MESSAGE_FORMAT_DATE_OCTOBER'			  : "MESSAGE_FORMAT_DATE_OCTOBER",
		'MESSAGE_FORMAT_DATE_NOVEMBER'			  : "MESSAGE_FORMAT_DATE_NOVEMBER",
		'MESSAGE_FORMAT_DATE_DECEMBER'			  : "MESSAGE_FORMAT_DATE_DECEMBER",
		'This field is required.' 				: "This field is required.",
		'Please fix this field.' 				: "Please fix this field.",
		'Please enter a valid email address.' 				: "Please enter a valid email address.",
		'Please enter a valid URL.' 				: "Please enter a valid URL.",
		'Please enter a valid date.' 				: "Please enter a valid date.",
		'Please enter a valid date (ISO).' 				: "Please enter a valid date (ISO).",
		'Please enter a valid number.' 				: "Please enter a valid number.",
		'Please enter only digits.' 				: "Please enter only digits.",
		'Please enter the same value again.' 				: "Please enter the same value again.",
		'Please enter a value with a valid extension.' 				: "Please enter a value with a valid extension.",
		'Please enter no more than {0} characters.' 				: "Please enter no more than {0} characters.",
		'Please enter at least {0} characters.' 				: "Please enter at least {0} characters.",
		'Please enter a value between {0} and {1} characters long.': "Please enter a value between {0} and {1} characters long.",
		'Please enter a value between {0} and {1}.' 				: "Please enter a value between {0} and {1}.",
		'Please enter a value less than or equal to {0}.' 				: "Please enter a value less than or equal to {0}.",
		'Please enter a value greater than or equal to {0}.' 				: "Please enter a value greater than or equal to {0}.",
		'USB IP Address must be valid and in the correct subnet.' 				: "USB IP Address must be valid and in the correct subnet.",
		'Please select an exported configuration file' 				: "Please select an exported configuration file",
		'Please select an upgrade (.spk) file'						: "Please select an upgrade (.spk) file",
		'Please enter a valid PIN.' 				: "Please enter a valid PIN.",
		'Please enter a number between 0 and 2347' 				: "Please enter a number between 0 and 2347",
		'Please enter a number between 256 and 2346' 				: "Please enter a number between 256 and 2346",
		'Please enter exactly {0} characters.' 				: "Please enter exactly {0} characters.",
		'Please enter a valid MAC address.' 				: "Please enter a valid MAC address.",
		'This device had been added to the list already.'       : "This device had been added to the list already",
		'MESSAGE_INVALID_IP_ADDRESS' 				: "MESSAGE_INVALID_IP_ADDRESS",
		'MESSAGE_INVALID_IP_RANGE' 				: "MESSAGE_INVALID_IP_RANGE",
		'MESSAGE_RESERVED_IP_ADDRESS' 				: "MESSAGE_RESERVED_IP_ADDRESS",
		'MESSAGE_IP_EQUAL_NETMASK_RANGE' 				: "MESSAGE_IP_EQUAL_NETMASK_RANGE",
		'Please enter a valid IP address.' 				: "Please enter a valid IP address.",
		'Please enter a valid password.' 				: "Please enter a valid password.",
		'Passwords must match.' 				: "Passwords must match.",
		'Password must match.' 				: "Password must match.",
		'NEW and VERIFY SIM PIN must match.' 				: "NEW and VERIFY SIM PIN must match.",
		'Please enter a valid PUK.' 				: "Please enter a valid PUK.",
		'Please enter a valid name.' 				: "Please enter a valid name.",
		'SIM Blocked'								: "SIM Blocked",
		'SIM Locked'								: "SIM Locked",
		'Device Locked'								: "Device Locked",
		'If you have a device unlock code please click below to enter it, otherwise contact your network provider for the unlock code.'		: "If you have a mobile router unlock code please click below to enter it, otherwise contact your network provider for the unlock code.",
		'SIM MEP Blocked'							: "SIM MEP Blocked",
		'SIM PIN Accepted'							: "SIM PIN Accepted",
		'Invalid SIM PIN. You have'					: "Invalid SIM PIN. You have",
		'entries left'								: "entries left",
		'SIM PUK Accepted'							: "SIM PUK Accepted",
		'Invalid SIM PUK'							: "Invalid SIM PUK",
		'Unlock Code Accepted'						: "Unlock Code Accepted",
		'Invalid Unlock Code'						: "Invalid Unlock Code",
		'ENTER_VALID_MEPCODE'						: "ENTER_VALID_MEPCODE",
		'Please enter a valid APN.' 				: "Please enter a valid APN.",
		'Please enter a valid username.' 				: "Please enter a valid username.",
		'Please enter a valid SSID.' 				: "Please enter a valid SSID.",
		'Main and Guest network name need to be unique.' 				: "Main and Guest network name need to be unique.",
		'Each LTE band must have a unique priority' 				: "Each LTE band must have a unique priority",
		'Please enter a valid hostname.' 				: "Please enter a valid hostname.",
		'Please enter a valid WiFi Password.' 			: "Please enter a valid WiFi Password.",
		'Please enter a valid phone number.'			: "Please enter a valid phone number.",
		'Please contact your network provider'			: "Please contact your network provider",
		// TODO, these should be built into proper strings for languages with different word order.
		'THE_PASSWORD_LENGTH_SHOULD_BE'					: "THE_PASSWORD_LENGTH_SHOULD_BE",
		'BETWEEN'										: "BETWEEN",
		'AND'											: "AND",
		'CHARACTERS_LONG'								: "CHARACTERS_LONG",
		'DATAUSAGE_STRING_DAY'							: "DATAUSAGE_STRING_DAY",
		'DATAUSAGE_STRING_DAYS'							: "DATAUSAGE_STRING_DAYS",
		'MOBILE_SHARE_HEADING'							: "Mobile Share {0} Plan",
		'MOBILE_SHARE_A_HEADING'						: "Mobile Share Advantage {0} Plan",
		'MOBILE_SHARE_UNLIMITED_HEADING'				: "Mobile Share Unlimited Plan",
		'MOBILE_SHARE_A_UNLIMITED_HEADING'				: "Mobile Share Advantage Unlimited Plan",
		'INDIVIDUAL_PLAN_HEADING'						: "DataConnect {0} Plan",
		'INDIVIDUAL_PLAN_PREPAID_HEADING'				: "DataConnect Pass {0} Plan",
		'UNLIMITED_PLAN_HEADING'						: "Data Unlimited",
		'ROAMING_HEADING'								: "Int'l Roaming",
		'GOPHONE_HEADING'								: "AT&amp;T PREPAID<sup>SM</sup>",
		'UNAVAILABLE_HEADING'							: "Data Unavailable",	
		'ROLLOVER_DATA_USAGE_NOTE'						: "*includes {0} of Rollover Data",
		'WITH ROLLOVER DATA'							: "with Rollover Data",

		'DATA_USAGE_NOTE_POSTPAID'						: "<strong>You’re on track</strong><br/>You're unlikely to exceed your data plan this month.",
		'DATA_USAGE_NOTE_OVERAGE_POSTPAID'				: "<strong>You’re in overage</strong><br/>Learn more about data plans that fit your needs at att.com/plans.",
		'DATA_USAGE_NOTE_OVER_POSTPAID'					: "<strong>Proceed with caution</strong><br/>Based on your usage, you will exceed your data plan this month",
		'DATA_USAGE_NOTE_NOPLAN_PREPAID'				: "You currently have no additional plans.",
		'DATA_USAGE_NOTE_WITH_PLAN_PREPAID'				: "You currently have one stacked plan that begins on {0}",
		'Software mismatch'								: "Software mismatch",
		'The session could not be completed'			: "The session could not be completed and the device will automatically retry the check for an available update.",
		'Update error'									: "There was a problem updating your device. Please try again later.",
		'Software up to date'							: "Current software is up to date.",
        'ALERT_RTN_RESET'								: "ALERT_RTN_RESET",
        'LABEL_LAST_RESET_CUSTOM_FORMAT'				: "LABEL_LAST_RESET_CUSTOM_FORMAT",
        'DATA_COMPANY_INFO_LINK'						: "DATA_COMPANY_INFO_LINK",
        'DATA_COMPANY_INFO_LINK_MYACCOUNT'				: "DATA_COMPANY_INFO_LINK_MYACCOUNT",
        'BILLING_DAY_LABEL'								: "Day {0} each month",
        'INVALID_DATA_LIMIT'							: "Data limit is invalid",
        'NETWORK_DISCONNECTED'							: "NETWORK_DISCONNECTED",
        'CONNECTION_NO_SIM'								: "CONNECTION_NO_SIM",
        'CONNECTION_AIRPLANE_MODE'						: "CONNECTION_AIRPLANE_MODE",
        'LIST_ROW_REMOVE'								: "LIST_ROW_REMOVE",
        'NOT_AVAILABLE'									: "NOT_AVAILABLE",
        'NOT_AVAILABLE_LONG'							: "NOT_AVAILABLE_LONG",
        'MESSAGE_BAND_REGION-Automatic'					: "MESSAGE_BAND_REGION-Automatic",	
		'MESSAGE_BAND_REGION-LTEOnly'					: "MESSAGE_BAND_REGION-LTEOnly",
		'MESSAGE_BAND_REGION-LTE_ALL'					: "MESSAGE_BAND_REGION-LTE_ALL",		
		'MESSAGE_BAND_REGION-CDMAOnly'					: "MESSAGE_BAND_REGION-CDMAOnly",	
		'MESSAGE_BAND_REGION-WCDMAOnly'					: "MESSAGE_BAND_REGION-WCDMAOnly",		
		'MESSAGE_BAND_REGION-WCDMA_ALL'					: "MESSAGE_BAND_REGION-WCDMA_ALL",
		'MESSAGE_BAND_REGION-ALLBANDS'					: "All Bands",
		'MESSAGE_BAND_REGION-4GOnly'					: "4G Only",
		'MESSAGE_BAND_REGION-3GOnly'					: "3G Only",
		'MESSAGE_BAND_REGION-EUROPE'					: "MESSAGE_BAND_REGION-EUROPE",
		'MESSAGE_BAND_REGION-EUROPE_3G'					: "MESSAGE_BAND_REGION-EUROPE_3G",
		'MESSAGE_BAND_REGION-NORTH_AMERICA'				: "MESSAGE_BAND_REGION-NORTH_AMERICA",
		'MESSAGE_BAND_REGION-NORTH_AMERICA_3G'			: "MESSAGE_BAND_REGION-NORTH_AMERICA_3G",
		'MESSAGE_POWER_PMSTATE-Online'					: "MESSAGE_POWER_PMSTATE-Online",
		'MESSAGE_POWER_PMSTATE-Offline'					: "MESSAGE_POWER_PMSTATE-Offline",
		'MESSAGE_POWER_PMSTATE-Init'					: "MESSAGE_POWER_PMSTATE-Init",
		'MESSAGE_POWER_PMSTATE-LowPower'				: "MESSAGE_POWER_PMSTATE-LowPower",
		'MESSAGE_POWER_PMSTATE-Standby'					: "MESSAGE_POWER_PMSTATE-Standby",
		'MESSAGE_POWER_BATTERYSTATE-NoBattery'			: "MESSAGE_POWER_BATTERYSTATE-NoBattery",
		'MESSAGE_POWER_BATTERYSTATE-Normal'				: "MESSAGE_POWER_BATTERYSTATE-Normal",
		'MESSAGE_POWER_BATTERYSTATE-Low'				: "MESSAGE_POWER_BATTERYSTATE-Low",
		'MESSAGE_POWER_BATTERYSTATE-Critical'			: "MESSAGE_POWER_BATTERYSTATE-Critical",
		'MESSAGE_POWER_BATTERYSTATE-Unknown'			: "MESSAGE_POWER_BATTERYSTATE-Unknown",
		'LABEL_WIFI_TXPOWER_OPTION-Short'				: "LABEL_WIFI_TXPOWER_OPTION-Short",
		'LABEL_WIFI_TXPOWER_OPTION-Medium'				: "LABEL_WIFI_TXPOWER_OPTION-Medium",
		'LABEL_WIFI_TXPOWER_OPTION-Long'				: "LABEL_WIFI_TXPOWER_OPTION-Long",
		'MESSAGE_NO_DEVICES_CONNECTED'					: "MESSAGE_NO_DEVICES_CONNECTED",
		'MESSAGE_NO_DEVICES_BLOCKED'					: "MESSAGE_NO_DEVICES_BLOCKED",
		'SCANNING_NETWORKS'								: "SCANNING_NETWORKS",
		'HIDE_PASSWORD_TEXT' 							: "HIDE_PASSWORD_TEXT",
        'SHOW_PASSWORD_TEXT' 							: "SHOW_PASSWORD_TEXT", 
        'TELSTRA_HOME_PAGE' 							: "TELSTRA_HOME_PAGE",
        'TELSTRA_BOOKMARK_MSG'							: "TELSTRA_BOOKMARK_MSG",
        'Of' 											: "Of",
        'DATA_USAGE_LEFT_TEXT'		 					: "DATA_USAGE_LEFT_TEXT",
        'DATA_USAGE_DATA_USED_TEXT'						: "Data Used",
        'DATA_USAGE_DATA_OVER_TEXT'						: "DATA_USAGE_DATA_OVER_TEXT",
        'ALT_METRIC_TEXT'		 						: "ALT_METRIC_TEXT",
        'LABEL_WIFI_SSID'								: "Wi-Fi Name",
        'LABEL_WIFI_(SSID)'								: "Wi-Fi Name (SSID)",
		'LABEL_WIFI_PASSPHRASE'							: "Wi-Fi Password",
		'LABEL_WIFI_GUEST_SSID'							: "LABEL_WIFI_GUEST_SSID",
		'LABEL_WIFI_GUEST_PASSPHRASE'					: "LABEL_WIFI_GUEST_PASSPHRASE",
		'LABEL_WEBD_ADMINPASSWORD'						: "Password",
		'BADGE_WIFI_MAIN' 								: "BADGE_WIFI_MAIN",
		'BADGE_WIFI_SECONDARY' 							: "BADGE_WIFI_SECONDARY",
		'BADGE_WIFI_GUEST' 								: "BADGE_WIFI_GUEST",
		'BADGE_WIFI_24GHZ' 								: "BADGE_WIFI_24GHZ", 
		'BADGE_WIFI_5GHZ' 								: "BADGE_WIFI_5GHZ",
		'BADGE_USB' 									: "BADGE_USB",
		'SESSION_DURATION_MINUTE'						: "m",
        'SESSION_DURATION_MINUTES'						: "m",
        'SESSION_DURATION_SECONDS'						: "s",
        'SESSION_DURATION_HOURS'						: "h ",
        'SESSION_DURATION_DAYS'							: "d ",
		'NETWORK_SEARCHING'								: "NETWORK_SEARCHING",
		'LBS_METRIC_DISTANCE_UNITS'						: "LBS_METRIC_DISTANCE_UNITS",
		'LBS_IMPERIAL_DISTANCE_UNITS'					: "LBS_IMPERIAL_DISTANCE_UNITS",
		'LBS_METRIC_SPEED_UNITS'						: "LBS_METRIC_SPEED_UNITS",
		'LBS_IMPERIAL_SPEED_UNITS'						: "LBS_IMPERIAL_SPEED_UNITS",
		'FOTA_GBYTE'									: "GB",
		'FOTA_MBYTE'									: "MB",
		'FOTA_KBYTE'									: "KB",
		'DATAUSAGE_ROAMING'								: "DATAUSAGE_ROAMING",
		'DATAUSAGE_DOMESTIC_LIMITED'					: "DATAUSAGE_DOMESTIC_LIMITED",
		'DATAUSAGE_DOMESTIC_UNLIMITED'					: "DATAUSAGE_DOMESTIC_UNLIMITED",
		'LABEL_TEXT_NO_BATTERY'							: "LABEL_TEXT_NO_BATTERY",
		'ADMIN_LOGIN_INCORRECT'							: "ADMIN_LOGIN_INCORRECT",
		'TITLE_APN_ACTIVE'								: "TITLE_APN_ACTIVE",
		'WIFI_AUTO_CHANNEL_SELECTION'					: "WIFI_AUTO_CHANNEL_SELECTION",
		'LABEL_WIFI_CHANNEL_OPTION-0'					: "LABEL_WIFI_CHANNEL_OPTION-0",
		'MESSAGE_INVALID_DHCP_RANGE'					: "MESSAGE_INVALID_DHCP_RANGE",
		'TIME_FORMAT'									: "%h:%i %A",
		'POWER_SHUTTING_DOWN_TEXT'						: "POWER_SHUTTING_DOWN_TEXT",  
		'BUTTON_SMS_DELETE'								: "BUTTON_SMS_DELETE",
		'BUTTON_SAVE_ROW'								: "BUTTON_SAVE_ROW",
		'BUTTON_EDIT_ROW'								: "BUTTON_EDIT_ROW",
		'BUTTON_DETAILS_ROW'							: "BUTTON_DETAILS_ROW",
		'BUTTON_CLOSE_ROW'								: "BUTTON_CLOSE_ROW",
		'BUTTON_DELETE_ROW'								: "BUTTON_DELETE_ROW",
		'BUTTON_CANCEL_ROW'								: "BUTTON_CANCEL_ROW",
		'BUTTON_ADD_ROW'								: "BUTTON_ADD_ROW",
		
		'SELECT_NETWORK'								: "Select Network...",
		'MO_SMS_MAX_CHARS'								: "MO_SMS_MAX_CHARS",
		'SMS_RECEIVED_FORMAT'							: "SMS_RECEIVED_FORMAT",
		'LABEL_SMS_TO'									: "LABEL_SMS_TO",
		'LABEL_SMS_MESSAGE'								: "LABEL_SMS_MESSAGE",
		'LABEL_PADALPHAENTER_DONE'						: "LABEL_PADALPHAENTER_DONE",
		'LABEL_PADALPHAENTER_NEXT'						: "LABEL_PADALPHAENTER_NEXT",
		'LABEL_SMS_NUMBER'								: "LABEL_SMS_NUMBER",
		'LABEL_SMS_ENTERMESSAGE'						: "LABEL_SMS_ENTERMESSAGE",
		'BUTTON_SMS_SEND'								: "BUTTON_SMS_SEND",
		'DATA_USAGE_TRANSFORMER_TIME_FORMAT'			: "%M %d %Y",
		'DATA_USAGE_TRANSFORMER_TIME_FULL_FORMAT'		: "%h %A {0}",
		'DATA_USAGE_TRANSFORMER_TIME_SHORT_FORMAT'		: "%M %d",		
		'ALERT_UNKNOWN_ACCOUNT_TEXT'           		    : "ALERT_UNKNOWN_ACCOUNT_TEXT",
		'LABEL_NOT_ACTIVATED'							: "LABEL_NOT_ACTIVATED",
		'TEXT_RECONDITIONED_NO'							: "TEXT_RECONDITIONED_NO",
		'TEXT_RECONDITIONED_YES'						: "TEXT_RECONDITIONED_YES",
		'TEXT_DEVICE_RESTARTING'						: "TEXT_DEVICE_RESTARTING",
		'TEXT_RESET_ERROR_RESTARTING'					: "TEXT_RESET_ERROR_RESTARTING",
        'DATA_USAGE_PLAN_USED_TEXT'						: "DATA_USAGE_PLAN_USED_TEXT",
        'DATA_USAGE_UNLIMITED_USED_TEXT'				: " Unlimited Used",
        'DATA_USAGE_INTERNATIONAL_USED_TEXT'			: "of International Roaming Used",
        'DATA_USAGE_UNAVAILABLE_TEXT'					: "{0} Used",
        'DATA_USAGE_INTL_USED_TEXT'						: "DATA_USAGE_INTL_USED_TEXT",
        'ROAMING_DATA_DISABLED'							: "Roaming Data Disabled",
        'ANNOUNCE_WEB_POSTPAID_MID_TEXT'				: "ANNOUNCE_WEB_POSTPAID_MID_TEXT",
        'ANNOUNCE_WEB_POSTPAID_LOW_TEXT'				: "ANNOUNCE_WEB_POSTPAID_LOW_TEXT",
        'ANNOUNCE_WEB_POSTPAID_CRITICAL_TEXT'			: "ANNOUNCE_WEB_POSTPAID_CRITICAL_TEXT",
        'ANNOUNCE_POSTPAID_MID_SHAPING'					: "ANNOUNCE_POSTPAID_MID_SHAPING",
        'ANNOUNCE_POSTPAID_LOW_SHAPING'					: "ANNOUNCE_POSTPAID_LOW_SHAPING",
        'ANNOUNCE_POSTPAID_CRITICAL_SHAPING'			: "ANNOUNCE_POSTPAID_CRITICAL_SHAPING",
        'ALERT_POSTPAID_MID_TEXT'						: "ALERT_POSTPAID_MID_TEXT",
        'ALERT_POSTPAID_LOW_TEXT'						: "ALERT_POSTPAID_LOW_TEXT",
        'ALERT_POSTPAID_CRITICAL_TEXT'					: "ALERT_POSTPAID_CRITICAL_TEXT",
        'ALERT_POSTPAID_MID_SHAPING'					: "ALERT_POSTPAID_MID_SHAPING",
        'ALERT_POSTPAID_MID_SHAPING_ACTIVE'				: "ALERT_POSTPAID_MID_SHAPING_ACTIVE",
        'ALERT_POSTPAID_LOW_SHAPING'					: "ALERT_POSTPAID_LOW_SHAPING",
        'ALERT_POSTPAID_LOW_SHAPING_ACTIVE'				: "ALERT_POSTPAID_LOW_SHAPING_ACTIVE",
        'ALERT_POSTPAID_CRITICAL_SHAPING'				: "ALERT_POSTPAID_CRITICAL_SHAPING",
        'ALERT_POSTPAID_CRITICAL_SHAPING_ACTIVE'		: "ALERT_POSTPAID_CRITICAL_SHAPING_ACTIVE",
        'DATA_SHAPING_NOTE'								: "DATA_SHAPING_NOTE",
        'DATA_SHAPING_ACTIVE_NOTE'						: "DATA_SHAPING_ACTIVE_NOTE",
        'DATA_COMPANY_INFO'								: "DATA_COMPANY_INFO",
        'DATA_COMPANY_INFO_SHAPING'						: "DATA_COMPANY_INFO_SHAPING",
        'DATA_COMPANY_INFO_PREPAID'						: "DATA_COMPANY_INFO_PREPAID",
        'ANNOUNCE_SAFETY_NET_READY'						: "ANNOUNCE_SAFETY_NET_READY",
        'ANNOUNCE_SAFETY_NET_ACTIVE'					: "ANNOUNCE_SAFETY_NET_ACTIVE",
        'PROGRESS_APPLYING_CHANGES'						: "PROGRESS_APPLYING_CHANGES",
        
        'RESETTING'										: "RESETTING",
        'TITLE_NEW_APN'									: "TITLE_NEW_APN",
		'BADGE_WIFI_SECONDARY'							: "BADGE_WIFI_SECONDARY",
		'BADGE_WIFI_GUEST'								: "BADGE_WIFI_GUEST",
		'CUSTOM'										: "CUSTOM",
		'MESSAGE_WWAN_CONNECTION-Connecting'			: "MESSAGE_WWAN_CONNECTION-Connecting",
		'-5GHz_Profile_Suffix'							: "-5GHz_Profile_Suffix",
		'Guest_Profile_Suffix'							: "Guest_Profile_Suffix",
		'LABEL_BACK'									: "LABEL_BACK",
		'LABEL_DEVICES_NAME'							: "LABEL_DEVICES_NAME",
		'LABEL_DEVICES_NETWORK'							: "LABEL_DEVICES_NETWORK",
		'LABEL_DEVICES_IP'								: "LABEL_DEVICES_IP",
		'LABEL_DEVICES_MAC'								: "LABEL_DEVICES_MAC",
		'LABEL_NO_DEVICES_CONNECTED'					: "LABEL_NO_DEVICES_CONNECTED",
		'LABEL_NO_MORE_BLOCKED_DEVICES'					: "LABEL_NO_MORE_BLOCKED_DEVICES",
		'LABEL_NO_MORE_CONNECTED_DEVICES'				: "LABEL_NO_MORE_CONNECTED_DEVICES",
		'LABEL_NO_BLOCKED_DEVICES'						: "LABEL_NO_BLOCKED_DEVICES",
		'LABEL_NO_TETHERED_DEVICES'						: "LABEL_NO_TETHERED_DEVICES",
		'LABEL_WIFI_BANDWIDTH_OPTION-HT20'				: "LABEL_WIFI_BANDWIDTH_OPTION-HT20",
		'LABEL_WIFI_BANDWIDTH_OPTION-HT40'				: "LABEL_WIFI_BANDWIDTH_OPTION-HT40",
		'LABEL_WIFI_BANDWIDTH_OPTION-VHT80'				: "LABEL_WIFI_BANDWIDTH_OPTION-HT80",
		'FOTA_LASTCHKDATE_FORMAT'				 		: "FOTA_LASTCHKDATE_FORMAT",
		'FOTA_NONEWFW_LASTCHKDATE'				 		: "Up to date - Last checked {0}",
		'FOTA_LASTCHKDATE'				 				: "Last checked {0}",
		'UPDATE_SUCCESS_CLEAR_CACHE'					: "Success: New firmware successfully installed. <br>You may need to clear your browser cache for the changes to take effect. To clear the cache &quot;Hold down Ctrl and press F5&quot;.",
		'FOTA_SUPPRESS_DOWNLOAD'						: "Insufficient data to download update",
		'FOTA_DISABLED_NOT_IN_SERVICE'					: "Updates disabled while device not in service",
		'FOTA_DISABLED_ROAMING'							: "Updates disabled while roaming",
		'CP_LOGIN_TIMEOUT_FORMAT'				 		: "CP_LOGIN_TIMEOUT_FORMAT",
		'LABEL_WWAN_ROAMING'							: "LABEL_WWAN_ROAMING",
		'WPS_24GHZ_TITLE'								: "WPS_24GHZ_TITLE",
		'WPS_5GHZ_TITLE'								: "WPS_5GHZ_TITLE",
		'WPS_MAIN_DESCRIPTION'							: "WPS_MAIN_DESCRIPTION",
		'WPS_GUEST_DESCRIPTION'							: "WPS_GUEST_DESCRIPTION",
		'WPS_24GHZ_DESCRIPTION'							: "WPS_24GHZ_DESCRIPTION",
		'WPS_5GHZ_DESCRIPTION'							: "WPS_5GHZ_DESCRIPTION",
		'LABEL_WWAN_CURRENTPSSERVICETYPE_OPTION-NONE'	: "LABEL_WWAN_CURRENTPSSERVICETYPE_OPTION-NONE",
		'LABEL_WWAN_CURRENTPSSERVICETYPE_OPTION-GPRS'	: "LABEL_WWAN_CURRENTPSSERVICETYPE_OPTION-GPRS",
		'LABEL_WWAN_CURRENTPSSERVICETYPE_OPTION-EDGE'	: "LABEL_WWAN_CURRENTPSSERVICETYPE_OPTION-EDGE",
		'LABEL_WWAN_CURRENTPSSERVICETYPE_OPTION-UMTS'	: "LABEL_WWAN_CURRENTPSSERVICETYPE_OPTION-UMTS",
		'LABEL_WWAN_CURRENTPSSERVICETYPE_OPTION-HSDPA'	: "LABEL_WWAN_CURRENTPSSERVICETYPE_OPTION-HSDPA",
		'LABEL_WWAN_CURRENTPSSERVICETYPE_OPTION-HSUPA'	: "LABEL_WWAN_CURRENTPSSERVICETYPE_OPTION-HSUPA",
		'LABEL_WWAN_CURRENTPSSERVICETYPE_OPTION-HSPA'	: "LABEL_WWAN_CURRENTPSSERVICETYPE_OPTION-HSPA",
		'LABEL_WWAN_CURRENTPSSERVICETYPE_OPTION-HSPA_PLUS'	: "LABEL_WWAN_CURRENTPSSERVICETYPE_OPTION-HSPA_PLUS",
		'LABEL_WWAN_CURRENTPSSERVICETYPE_OPTION-DC_HSPA_PLUS'	: "LABEL_WWAN_CURRENTPSSERVICETYPE_OPTION-DC_HSPA_PLUS",
		'LABEL_WWAN_CURRENTPSSERVICETYPE_OPTION-LTE'	: "LABEL_WWAN_CURRENTPSSERVICETYPE_OPTION-LTE",
		'BUTTON_WIFI_WPS_MAIN'							: "BUTTON_WIFI_WPS_MAIN",
		'BUTTON_WIFI_WPS_GUEST'							: "BUTTON_WIFI_WPS_GUEST",
		'BUTTON_WIFI_WPS_24GHZ'							: "BUTTON_WIFI_WPS_24GHZ",
		'BUTTON_WIFI_WPS_5GHZ'							: "BUTTON_WIFI_WPS_5GHZ",
		'TITLE_GUEST_WIFI'								: "TITLE_GUEST_WIFI",
		'TITLE_WIFI_DEVICES_MAIN'						: "TITLE_WIFI_DEVICES_MAIN",
		'TITLE_WIFI_DEVICES_GUEST'						: "TITLE_WIFI_DEVICES_GUEST",
		'TITLE_WIFI_DEVICES_24GHZ'						: "TITLE_WIFI_DEVICES_24GHZ",
		'TITLE_WIFI_DEVICES_5GHZ'						: "TITLE_WIFI_DEVICES_5GHZ",
		'LABEL_GUEST_WIFI_NAME'							: "LABEL_GUEST_WIFI_NAME",
		'LABEL_GUEST_WIFI_PASSWORD'						: "LABEL_GUEST_WIFI_PASSWORD",
		'LABEL_EDIT_DUAL_NAME'							: "LABEL_EDIT_DUAL_NAME",
		'LABEL_EDIT_DUAL_PASSWORD'						: "LABEL_EDIT_DUAL_PASSWORD",
		'RECHARGE_FAILED'								: "RECHARGE_FAILED",
		'RECHARGE_FAILED_INVALID_PIN'					: "RECHARGE_FAILED_INVALID_PIN",
		'RECHARGE_FAILED_INSUFFICIENT_BALANCE'			: "RECHARGE_FAILED_INSUFFICIENT_BALANCE",
		'BUTTON_SUBMIT'									: "Submit",
		'BATTERY_LOW_TO_UPLOAD_FILE'					: "Software Update available when battery level is greater than {minPowerPercent}%",
		'LABEL_WIFI_PROFILE_DEFAULT'					: "LABEL_WIFI_PROFILE_DEFAULT",
		'LABEL_WIFI_PROFILE_WIFI5GHZ'					: "LABEL_WIFI_PROFILE_WIFI5GHZ",
		'TIME_AM_FORMAT'								: "TIME_AM_FORMAT",
		'TIME_am_FORMAT'								: "TIME_am_FORMAT",
		'TIME_PM_FORMAT'								: "TIME_PM_FORMAT",
		'TIME_pm_FORMAT'								: "TIME_pm_FORMAT",
		'MAGIC_ON_VALUE'								: "MAGIC_ON_VALUE",
		'TITLE_VERIFY_NEW_SIM_PIN'						: "TITLE_VERIFY_NEW_SIM_PIN",
		'BUTTON_OK'										: "BUTTON_OK",
		'BUTTON_CANCEL'									: "BUTTON_CANCEL",
		'BUTTON_CONFIRM_CONFIRM'						: "BUTTON_CONFIRM_CONFIRM",
		'BUTTON_DISMISS'								: "BUTTON_DISMISS",
		
		'LABEL_GUEST_TIMER_HOURS'						: "LABEL_GUEST_TIMER_HOURS",
		'LABEL_GUEST_TIMER_MINS'						: "LABEL_GUEST_TIMER_MINS",
		'SMALL_CIRCLE'									: "SMALL_CIRCLE",
		'REMAINING_GUEST_TIMER_HOUR'					: "REMAINING_GUEST_TIMER_HOUR",
		'REMAINING_GUEST_TIMER_HOURS'					: "REMAINING_GUEST_TIMER_HOURS",
		'REMAINING_GUEST_TIMER_MINS'					: "REMAINING_GUEST_TIMER_MINS",
		'REMAINING_GUEST_TIMER_HOUR_MIN'				: "REMAINING_GUEST_TIMER_HOUR_MIN",
		'REMAINING_GUEST_TIMER_HOUR_MINS'				: "REMAINING_GUEST_TIMER_HOUR_MINS",
		'REMAINING_GUEST_TIMER_HOURS_MIN'				: "REMAINING_GUEST_TIMER_HOURS_MIN",
		'REMAINING_GUEST_TIMER_HOURS_MINS'				: "REMAINING_GUEST_TIMER_HOURS_MINS",
		'REMAINING_GUEST_TIMER_ONE_MIN_OR_LESS'			: "REMAINING_GUEST_TIMER_ONE_MIN_OR_LESS",
		'TIP_GUEST_TIMER'								: "TIP_GUEST_TIMER",
		'TIP_WIFI_MAXCLIENTCNT'							: "TIP_WIFI_MAXCLIENTCNT",
		'TITLE_NO_SIM'									: "No SIM",
		'TITLE_SIM_ERROR'								: "SIM Error",
		'TITLE_DEVICE_LOCKED'							: "Device Locked",
		'TITLE_SIM_PIN_LOCKED'							: "SIM PIN Locked",
		'TITLE_SIM_PIN_BLOCKED'							: "SIM PIN Blocked",
		'WIFI_BADGE_SLEEPING'							: "WIFI_BADGE_SLEEPING",
		'WIFI_BADGE_DISABLED'							: "&UNESCWIFI_BADGE_DISABLED",
		'SECURITY_SIM_PIN'								: "SECURITY_SIM_PIN",
		'SECURITY_SIM_PUK'								: "SECURITY_SIM_PUK",
		'SECURITY_SIM_MEP'								: "SECURITY_SIM_MEP",
		'ENTER_SIM_PIN'									: "ENTER_SIM_PIN",
		'BUTTON_ENTER_SIM_PUK'							: "BUTTON_ENTER_SIM_PUK",
		'BUTTON_ENTER_SIM_MEP'							: "BUTTON_ENTER_SIM_MEP",
		'ROAMING_ON'									: "ROAMING_ON",
		'ROAMING_OFF'									: "ROAMING_OFF",
		'SHUTTING_DOWN_HOTSPOT_HELP'					: "SHUTTING_DOWN_HOTSPOT_HELP",
		'RESTARTING_HOTSPOT_HELP'						: "RESTARTING_HOTSPOT_HELP",
		'SHUTTING_DOWN_HOTSPOT_TEXT'					: "SHUTTING_DOWN_HOTSPOT_TEXT",
		'RESTARTING_HOTSPOT_TEXT'						: "RESTARTING_HOTSPOT_TEXT",
		'LOCKSCREEN_DATE_FORMAT'						: "LOCKSCREEN_DATE_FORMAT",
		'LABEL_DISABLED'								: "LABEL_DISABLED",
		'ALERT_MAXWIFI_DESCRIPTION'						: "ALERT_MAXWIFI_DESCRIPTION",
		'ALERT_MAXWIFI_DESCRIPTION_1DEVICE'				: "ALERT_MAXWIFI_DESCRIPTION_1DEVICE",
		'ALERT_MAXWIFIGUEST_DESCRIPTION'				: "ALERT_MAXWIFIGUEST_DESCRIPTION",
		'ALERT_MAXWIFIGUEST_DESCRIPTION_1DEVICE'		: "ALERT_MAXWIFIGUEST_DESCRIPTION_1DEVICE",
		'ErrorSavingChanges'                            : "Error Saving Changes",

		'VALIDATE_CONTENT_FILTER_PASSWORD'				: "Your password must be between 8 to 256 characters long. It should include at least one uppercase letter, lowercase letter, digit, and a special character (e.g. *, &#x24;).",
		'ContentFilterUsernameTaken'                    : "Username already in use. Please try another.",
        'ContentFilterRegistrationError'                : "Error creating account.",
        'ContentFilterBadCredentials'                   : "Bad Username/Password.",
        'ContentFilterEmailTaken'                       : "Email address already in use. Please try another.",
        'ContentFilterDeviceKeyExists'                  : "This mobile router appears to be registered with another OpenDNS account.  Please visit <a href='http://netgear.opendns.com/support/#faq15' target='_blank'>OpenDNS Support</a> for further resolution.",
        'ContentFilterPasswordContainsUsername'         : "Password must not contain part of your username.",
        'ContentFilterRequestFailed'                    : "Content Filter is powered by OpenDNS. In order to change configuration, a network connection is required.",
		'ARLO_ENABLE_NOT_ALLOWED'		 				: "Enabling Arlo requires your mobile router to be configured with 5GHz WiFi only. To continue, please reconnect to your mobile router's 5GHz WiFi ({0}) and try again.",
		'LABEL_WIFI_24GHZ'								: "WI-FI NETWORK(2.4 GHz)",
		'LABEL_WIFI_5GHZ'								: "WI-FI NETWORK(5 GHz)",
		'LABEL_24GHZ'									: "2.4 GHz Wi-Fi",
		'LABEL_5GHZ'									: "5 GHz Wi-Fi",
		'LABEL_WIRELESS_24GHZ'							: "2.4 GHz Wireless Network",
		'LABEL_WIRELESS_5GHZ'							: "5 GHz Wireless Network",
		'LABEL_ENCRYPTION_TYPE'							: "Encryption Type",
		'LABEL_CHANNEL'									: "Channel",
		'LABEL_BANDWIDTH'								: "Bandwidth",
		'LABEL_BROADCAST_WIFI_SSID'						: "Broadcast Wi-Fi Name SSID",
		'LABEL_ADD_APN'									: "Add APN",
		'BUTTON_ADD'									: "ADD",
		'LABEL_EDIT_APN'								: "EDIT APN",
		'BUTTON_SAVE'									: "SAVE",
		'PASSWORD_MISMATCH'								: "New and Repeat Password must match",
		'NOTE_WIFI_RESTART_1'							: "Note - your Wi-Fi connection will restart and you may need to manually reconnect to",
		'PASSWORD_LENGTH_LIMIT'							: "Password cannot be more than 32 characters long",
		'NOTE_WIFI_RESTART_2'							: "with password",
		'LABEL_ACTIVE'									: "Active",
		'LABEL_INACTIVE'								: "Inactive",
		'SIM_SECURITY_HELP'								: "Activating SIM Security will require you to enter a SIM PIN each time you power on the mobile router.",
		'SIM_BLOCKED'									: "SIM_BLOCKED",
		'SIM_PUK_REQUIRED'								: "Your SIM requires a PUK code to be entered. Please press the PUK Entry button below to enter the SIM PUK code.",
		'SIM_UNLOCK_CODE'								: "If you have a SIM unlock code please click below to enter it in, otherwise contact your network provider for the SIM unlock code.",
		'SOFTWARE_UPDATE_HELP'							: "The software update process will take several minutes and will not delete any personal data on your mobile router. All services will be suspended during the install.",
		'LABEL_WIFI_GENERATE_PASSPHRASE'				: "Generate Passphrase",
		'WiFi'											: "Wi-Fi",
		'Network'										: "Network",
		'NETWORK'										: "NETWORK",
		'Wireless'										: "Wireless",
		'NOTIFY_Invalid_IPV4_ADDRESS'					: "Please enter a valid IPv4 address",
"Invalid IP Address": "Invalid IP Address",
"Current": "Current",
"Home": "Home",
"Forbidden": "Forbidden",
"Yes": "Yes",
"No": "No",
"QuickCharge": "QuickCharge",
"OFF": "OFF",
"ON": "ON",	
"UPDATE": "UPDATE",
"INSTALL": "INSTALL",
"CHECKING...": "CHECKING...",
"DOWNLOADING...": "DOWNLOADING - {0}",
"DOWNLOADING -": "DOWNLOADING - {0}%",
"CHECK FOR UPDATES": "CHECK FOR UPDATES",
"DOWNLOAD": "DOWNLOAD",
"NEW_UPDATE": "New Update Available. A ",
"NEW_UPDATE_HELP": " update is available for your mobile router which improves performance, stability and fixes bugs. Downloading over a mobile network or while roaming may cause additional charges.",
"UPDATING...": "UPDATING...",
"INSTALLING...": "INSTALLING...",
"Update was postponed": "Update was postponed.",
"Update was postponed for 4 hours": "Update was postponed for 4 hours",
"Unable to complete update. Connect device to the charger. Update will resume when battery level is at least 20%.": "Unable to complete update. Connect mobile router to the charger. Update will resume when battery level is at least 20%.",	
"Update currently downloading.": "Update currently downloading.",
"Operation of the device is not affected, and you may continue to use the device.": "Operation of the mobile router is not affected, and you may continue to use the mobile router.",
"Device Information": "Device Information",
"Connection Type": "Connection Type",
"IP Address": "IP Address",
"MAC Address": "MAC Address",

"Password is required": "Password is required",
"Username is required": "Username is required",
"MAC Address is invalid": "MAC Address is invalid",
"Password is required and must match confirm password": "Password is required and must match confirm password",
"Logged In": "Logged In",
"Logged Out": "Logged Out",
"Error logging out.": "Error logging out.",
"DHCP low must be lower than DHCP high": "DHCP low must be lower than DHCP high",
"Ip Address cannot be in dhcp range": "IP Address cannot be in DHCP range",
"Please use an IP address within DHCP range": "Please use an IP address within DHCP range",
"DNS Server 1 and DNS Server 2 should not be the same": "DNS Server 1 and DNS Server 2 should not be the same",

"Email is required and must match confirm email": "Email is required and must match confirm email",
"Error adding entry.": "Error adding entry.",
"New entry added.": "New entry added.",
"Error deleting entry.": "Error deleting entry.",
"Entry deleted.": "Entry deleted.",
"Service Name is required": "Service Name is required",
"IP is required and must be a valid address": "IP is required and must be a valid address",
"Port is required and must be a number": "Port is required and must be a number",
"Error adding entry. An Internet connection is required.": "Error adding entry. An Internet connection is required.",
"Label is needed": "Label is needed",
"At least one day must be selected": "At least one day must be selected",
"Start and End time are required": "Start and End time are required",

"Error updating entry.": "Error updating entry.",
"Entry updated.": "Entry updated.",
"Domain name is needed": "Domain name is needed",
"SSID already exists..": "SSID already exists..",
"No unrestricted devices.": "No unrestricted devices.",
"No portforwarding items": "No portforwarding items",
"No blocked devices.": "No blocked devices.",
"No allowed devices.": "No allowed devices.",
"No schedule items": "No schedule items",
"No domains in the domains table.": "No domains in the domains table.",
"No devices in the unrestricted devices table.": "No devices in the unrestricted devices table.",
"Add Website": "Add Website",
"ADD": "ADD",
"Edit Website": "Edit Website",
"SAVE": "SAVE",
"New Rule": "New Rule",
"Edit Rule": "Edit Rule",
"Block List": "Block List",
"Allow List": "Allow List",
"No blocked ports.": "No blocked ports.",
"No allowed ports.": "No allowed ports.",
"Service Name": "Service Name",
"Port": "Port",
'Message sent'									: "Message sent",
'Error sending message'							: "Error sending message",
'Please enter a valid phone number.'            : "Please enter a valid phone number.",
'Please enter a message.'                       : "Please enter a message.",
"Blacklist": "Blacklist",
"Whitelist": "Whitelist",
"Minimal": "Minimal",
"Low": "Low",
"Moderate": "Moderate",
"High": "High",
"Custom": "Custom",
"WwanOn": "WwanOn",
"WwanOff": "WwanOff",
"Initial": "Initial",
"DownloadAvailable": "DownloadAvailable",
"NoFwDownloadAvailable": "NoFwDownloadAvailable",
"Error": "Error",
"NoNewFw": "NoNewFw",
"FwQueryDownload": "FwQueryDownload",
"FwDownloading": "FwDownloading",
"FwDownloaded": "FwDownloaded",
"FwDownloadedError": "FwDownloadedError",
"FwQueryUpdate": "FwQueryUpdate",
"FwQueryCharger": "FwQueryCharger",
"FwPostponed": "FwPostponed",
"FwUpdating": "FwUpdating",
"FwUpdated": "FwUpdated",
"FwUpdatedError": "FwUpdatedError",
"NoRequest": "NoRequest",
"SPCLocked": "SPCLocked",
"SPCUnlocked": "SPCUnlocked",
"MaxSPCRetries": "MaxSPCRetries",
"Target": "Target",
"Simulation": "Simulation",
"NotStarted": "NotStarted",
"InProgress": "InProgress",
"Finished": "Finished",
"Failed": "Failed",
"Locked": "Locked",
"Unlocked": "Unlocked",
"Unknown": "SIM not ready - Unknown",
"StandAlone": "StandAlone",
"MSBased": "MSBased",
"MSAssisted": "MSAssisted",
"CellID": "CellID",
"Google": "Google",
"Yahoo": "Yahoo",
"MapQuest": "MapQuest",
"Bing": "Bing",
"Continuous": "Continuous",
"OneTime": "OneTime",
"Inactive": "Inactive",
"Bright": "Bright",
"Dim": "Dim",
"DC": "DC",
"PRL": "PRL",
"FUMO": "FUMO",
"HFADC": "HFADC",
"HFAPRL": "HFAPRL",
"HFAFUMO": "HFAFUMO",
"NI": "NI",
"SIMUNLOCK": "SIMUNLOCK",
"Idle": "Idle",
"Pending": "Pending",
"Init": "Init",
"Online": "Online",
"Offline": "Offline",
"LowPower": "LowPower",
"LowPowerMode": "LowPowerMode",
"PowerOff": "PowerOff",
"EnteringLowPowerMode": "EnteringLowPowerMode",
"Initialization": "Initialization",
"ChargeOnly": "ChargeOnly",
"ChargeTether": "ChargeTether",
"Normal": "Normal",
"ReduceStress": "ReduceStress",
"Heat": "Heat",
"GaugeMaintenance": "GaugeMaintenance",
"PC": "PC",
"Charger": "Charger",
"QuickCharge": "QuickCharge",
"NoBattery": "NoBattery",
"Critical": "Critical",
"Cold": "Cold",
"Hot": "Hot",
"Single": "Single",
"Double": "Double",
"NoAction": "NoAction",
"Prompt": "Prompt",
"NoResetRequired": "NoResetRequired",
"ProfileUpdated": "ProfileUpdated",
"Unregistered": "Unregistered",
"Registered": "Registered",
"RegistrationInProgress": "RegistrationInProgress",
"UnregistrationInProgress": "UnregistrationInProgress",
"RegistrationFailedInvalidAccountInfo": "RegistrationFailedInvalidAccountInfo",
"RegistrationFailedUnknown": "RegistrationFailedUnknown",
"UnregistrationFailedInvalidAccountInfo": "UnregistrationFailedInvalidAccountInfo",
"UnregistrationFailedUnknown": "UnregistrationFailedUnknown",
"Success": "Success",
"Fail": "Fail",
"FailBusy": "FailBusy",
"WhiteList": "WhiteList",
"BlackList": "BlackList",
"HID": "HID",
"SWOC": "SWOC",
"Modem": "Modem",
"PN": "PN",
"PU": "PU",
"PP": "PP",
"Enabled": "Enabled",
"NwSubset": "NwSubset",
"ServiceProvider": "ServiceProvider",
"Corporate": "Corporate",
"Initializing": "Initializing",
"Ready": "Ready",
"NotPresent": "NotPresent",
"InvalidCard": "InvalidCard",
"Failure": "SIM not ready - Failure",
"Blocked": "Blocked",
"Rejected": "SIM not ready - Rejected",
"MepLocked": "MepLocked",
"MepBlocked": "MepBlocked",
"SIM Not Installed": "SIM Not Installed",
"CallForwardingDisabled": "CallForwardingDisabled",
"CallForwardToUserNum": "CallForwardToUserNum",
"CallForwardToVoicemailAfterNumOfRings": "CallForwardToVoicemailAfterNumOfRings",
"Subscribed": "Subscribed",
"Suppression": "Suppression",
"Invocation": "Invocation",
"Full": "Full",
"VoiceCarryOver": "VoiceCarryOver",
"HearingCarryOver": "HearingCarryOver",
"HT20": "HT20",
"HT40": "HT40",
"VHT80": "VHT80",
"Guest": "Guest",
"Station": "Station",
"WEP64_Open": "WEP64_Open",
"WEP64_Shared": "WEP64_Shared",
"WEP128_Open": "WEP128_Open",
"WEP128_Shared": "WEP128_Shared",
"WPA_Personal_TKIP": "WPA_Personal_TKIP",
"WPA_Personal_TKIP_AES": "WPA_Personal_TKIP_AES",
"WPA2_Personal_AES": "WPA2_Personal_AES",
"WPA2_Personal_TKIP_AES": "WPA2_Personal_TKIP_AES",
"WPA_WPA2": "WPA_WPA2",
"M802_11_B": "M802_11_B",
"M802_11_G": "M802_11_G",
"M802_11_BG": "M802_11_BG",
"M802_11_BN": "M802_11_BN",
"M802_11_GN": "M802_11_GN",
"M802_11_BGN": "M802_11_BGN",
"M802_11_A": "M802_11_A",
"M802_11_AN": "M802_11_AN",
"M802_11_ANAC": "M802_11_ANAC",
"M802_11_AC": "M802_11_AC",
"Internet_Only": "Internet_Only",
"Started": "Started",
"FinishedSuccess": "FinishedSuccess",
"FinishedFail": "FinishedFail",
"Timeout": "Timeout",
"Disconnected": "Disconnected",
"Open": "Open",
"Secured": "Secured",
"Primary": "Primary",
"Aux": "Aux",
"PBC": "PBC",
"PIN": "PIN",
"Succeeded": "Succeeded",
"Both": "Both",
"NoService": "NoService",
"Limited": "Limited",
"FullService": "FullService",
"NotForcedDisabled": "NotForcedDisabled",
"NotForcedLTEOnlyEnabled": "NotForcedLTEOnlyEnabled",
"NotForcedeHRPDOnlyEnabled": "NotForcedeHRPDOnlyEnabled",
"NotForcedLTEAndeHRPDEnabled": "NotForcedLTEAndeHRPDEnabled",
"ForcedDisabled": "ForcedDisabled",
"ForcedLTEOnlyEnabled": "ForcedLTEOnlyEnabled",
"ForcedeHRPDOnlyEnabled": "ForcedeHRPDOnlyEnabled",
"ForcedLTEAndeHRPDEnabled": "ForcedLTEAndeHRPDEnabled",
"Only3G": "Only3G",
"Only2G": "Only2G",
"Preferred3G": "Preferred3G",
"Preferred2G": "Preferred2G",
"Only2G3G": "Only2G3G",
"Only4G": "Only4G",
"Only2G3G4G": "Only2G3G4G",
"Never": "Never",
"Always": "Always",
"HomeNetwork": "HomeNetwork",
"RoamNetwork": "RoamNetwork",
"Disconnecting": "Disconnecting",
"Connecting": "Connecting",
"IPv4Only": "IPv4Only",
"IPv6Only": "IPv6Only",
"IPv4AndIPv6": "IPv4AndIPv6",
"LimitedService": "LimitedService",
"GsmService": "GsmService",
"WcdmaService": "WcdmaService",
"LteService": "LteService",
"CdmaHrpdService": "CdmaHrpdService",
"HrpdService": "HrpdService",
"CdmaService": "CdmaService",
"GPRS": "GPRS",
"EDGE": "EDGE",
"UMTS": "UMTS",
"HSDPA": "HSDPA",
"HSUPA": "HSUPA",
"HSPA": "HSPA",
"HSPA_PLUS": "HSPA_PLUS",
"DC_HSPA_PLUS": "DC_HSPA_PLUS",
"LTE": "LTE",
"CDMA": "CDMA",
"HRPD": "HRPD",
"CDMA_HRPD": "CDMA_HRPD",
"GSM": "GSM",
"Postpaid": "Postpaid",
"Prepaid": "Prepaid",
"PrepaidAttGoPhone": "PrepaidAttGoPhone",
"Valid": "Valid",
"Invalid": "SIM not ready - Invalid",
"Invalid Email": "Invalid Email",
"Busy": "Busy",
"BillingCycle": "BillingCycle",
"CurrentSession": "CurrentSession",
"Warm": "Warm",
"PreActive": "PreActive",
"NotSpecified": "NotSpecified",
"KB": "KB",
"MB": "MB",
"GB": "GB",
"GB_USED": "<span class='m_datausage_dataTransferred'></span><h5>GB<br /> USED</h5>",
"MB_USED": "MB_USED",
"TB": "TB",
"ValidQueryFailed": "ValidQueryFailed",
"CSGInProgress": "CSGInProgress",
"CSGFinished": "CSGFinished",
"CSGFailed": "CSGFailed",
"Pass_Uname": "Pass_Uname",
"NotForcedEnabled": "NotForcedEnabled",
"ForcedEnabled": "ForcedEnabled",
"HomeOnly": "HomeOnly",
"Domestic": "Domestic",
"AllNetworks": "AllNetworks",
"DomesticOnly": "DomesticOnly",
"HomeAndDomestic": "HomeAndDomestic",
"HomeAndAllNetworks": "HomeAndAllNetworks",
"DomesticAndAllNetworks": "DomesticAndAllNetworks",
"All": "All",
"Home": "Home",
"International": "International",
"Dormant": "Dormant",
"Manual":  "Manual",
"Auto":  "Auto",
"Short":  "Short",
"Medium":  "Medium",
"Long":  "Long",
"Disabled":	  "Disabled",
"30 seconds":  "30 seconds",
"1 minute":  "1 minute",
"5 minutes":  "5 minutes",
"10 minutes":  "10 minutes",
"15 minutes":  "15 minutes",
"30 minutes":  "30 minutes",
"40 minutes":  "40 minutes",
"50 minutes":  "50 minutes",
"60 minutes":  "60 minutes",
"Excellent":  "Excellent",
"Good":  "Good",
"Fair":  "Fair",
"Poor":  "Poor",
"Entry updated":  "Entry updated",
"None": "None",
"Eject": "Eject",
"EjectHelp": "Safely eject your micro SD or USB drive before removing it from the mobile router.",
"CHARGE_TO_START_UPDATE": "To install, battery must be greater than {0}%.",

		
		
		

		'MAGIC_OFF_VALUE'								: "MAGIC_OFF_VALUE"
		
		
		
		
		
		
		
	};

     var _phrases = {
         "AjaxFileBrowser": {
             "Commands": {
                 "UndoCommand": "Undo {0}",
                 "CancelCommand": "Cancel {0}",
                 "Names": {
                     "Load": "Load",
                     "Copy": "Copy",
                     "CreateFolder": "Create Folder",
                     "Delete": "Delete",
                     "LoadFolder": "Load Folder",
                     "LoadItem": "Load Item",
                     "LoadTree": "Load Tree",
                     "Move": "Move",
                     "Rename": "Rename",
                     "Search": "Search"
                 },
                 "Process": {
                     "Load": "Loading...",
                     "Copy": "Copying &quot;{0}&quot;...",
                     "CreateFolder": "Creating Folder &quot;{0}&quot;...",
                     "Delete": "Deleting &quot;{0}&quot;...",
                     "LoadFolder": "Loading Folder &quot;{0}&quot;...",
                     "LoadItem": "Loading Item &quot;{0}&quot;...",
                     "LoadTree": "Loading Tree &quot;{0}&quot;...",
                     "Move": "Moving &quot;{0}&quot;...",
                     "Rename": "Renaming &quot;{0}&quot;...",
                     "Search": "Searching &quot;{0}&quot;..."
                 }
             },
             "Interface": {
                 "Buttons": {
                     "Copy": "Copy",
                     "CustomProp": "Custom Properties",
                     "Cut": "Cut",
                     "Close": "Close",
                     "Delete": "Delete",
                     "Details": "Details",
                     "Download": "Download",
                     "Edit": "Edit",
                     "ExtraLargeIcons": "Extra Large Icons",
                     "FileManager": "Open OS's File Manager.",
                     "Folders": "Folders",
                     "Info": "Properties",
                     "LargeIcons": "Large Icons",
                     "Lock": "Lock",
                     "Log": "Log",
                     "MediumIcons": "Medium Icons",
                     "NewFolder": "New Folder",
                     "Paste": "Paste",
                     "Redo": "Redo",
                     "Refresh": "Refresh",
                     "VersionUpdateToThis": "Update",
                     "VersionRemove": "Remove",
                     "VersionDownload": "Download",
                     "Versions": "Versions",
                     "Views": "Views",
                     "Undo": "Undo",
                     "Unlock": "Unlock",
                     "Up": "Up",
                     "Upload": "Upload",
                     "UploadFolder": "Upload Folder",
                     "Eject": "Eject",
                     "Play": "Play"
                 },
                 "OS": {
                     "Linux": "Linux",
                     "Windows": "Windows",
                     "MacOS": "OS X"
                 },
                 "Add": "Add",
                 "AddProperty": "Add Property",
                 "Address": "To open the files, select the file and click <div id='div_iconplay'></div> above.",
                 "BrowseFiles": "Browse...",
                 "Folder": "AjaxFileBrowser_Interface_Folder",
                 "BuyNow": "Buy Now",
                 "Cancel": "Cancel",
                 "CannotCreateDocument": "Selected document is not created.",
                 "CannotEditFile": "Current file cannot be opened for editing.",
                 "Close": "Close",
                 "CopyPattern": "Copy",
                 "Create": "Create",
                 "Created": "Created:",
                 "CrossDomainRequestsIssue": "Your server may not be configured to allow cross-domain requests.<br/>Please see how to enable cross-domain requests <a target='_blank' href='http://www.webdavsystem.com/ajaxfilebrowser/programming/cross_domain'>here</a>.<br/>",
                 "CrossDomainRequestsIssueIE": "Your Internet Explorer may not be configured to allow cross-domain requests.<br/>Please see how to enable cross-domain requests in Interner Explorer 9 and earlier <a target='_blank' href='http://www.webdavsystem.com/ajaxfilebrowser/programming/cross_domain'>here</a>.<br/>",
                 "CrossDomainRequestsIssueTitle": "Failed to connect to server",
                 "DateModified": "Date Modified",
                 "Delete": "Delete",
                 "DeleteItemsConfirmQuestion": "Are you sure you want to delete selected item(s)?",
                 "DeletePropertiesConfirmQuestion": "Are you sure want to delete selected property(s)?",
                 "DeleteVersionConfirmQuestion": "Are you sure want to delete selected version?",
                 "Details": "Details",
                 "DropFilesIEUnsupported": "Files drag and drop from file system is supported only in Internet Explorer 10, Microsoft Edge, Chrome 4, FireFox 3.6, Safari 4 and later versions.",
                 "Edit": "Edit",
                 "EditProperty": "Edit Рroperty",
                 "Error": "Error:",
                 "ErrorDetails": "Error Details",
                 "FailedToOpenWinExplorer": "Failed to open WebDAV folder in Windows Explorer.",
                 "File": "File",
                 "FileExistsOverwriteConfirmQuestion": "File &quot;{0}&quot; already exists. Do you want to overwrite it?",
                 "FileFolderType": "Folder",
                 "FileNameSpecialCharactersRestriction": "The name cannot contain any of the following characters:\n\t\t{0}",
                 "FilePrecentInUploadList": "Selected file is already present in upload list.",
                 "FilesPresentInUploadList": "The following file(s) is present in the upload list:\n\n{0}",
                 "FilesResumeNotInListOrChanged": "The following file(s) was modified:\n{0}\n\nThe following file(s) was not among your selection for resume in the upload list:\n{1}\n\nThe upload will start from the begging of each file.",
                 "FileUploadFailed": "Failed to upload the file.",
                 "FillOutFileName": "Specify the file name.",
                 "FillOutFolderName": "Specify the folder name.",
                 "FirefoxLargeFilesToUpload": "In Firefox files over 100 Mb cannot be uploaded together with other files or via drag and drop. The following files are too large:\n\n<b>{0}</b>\n\nTo upload this file(s) you must select them one by one using &quot;Browse...&quot; button or use other browser.",
                 "FirefoxFolderDropNotSupported": "Folders drag and drop is available only in Google Chrome 21 and later versions.",
                 "ItemAlreadyExists": "Item already exists.",
                 "FolderAlreadyExists": "Folder already exists.",
                 "FolderName": "Folder name",
                 "FolderUploadNotAvailedInYourBrowser": "Folders upload is available only in Google Chrome 21 and later versions.",
                 "FollowingErrorsOccurred": "The Following Errors Has Occurred",
                 "FreeSpace": "Free space:",
                 "GetPropertiesError": "Properties are not selected.",
                 "GetVersionsError": "Versions are not selected.",
                 "HttpNotAvailableError": "Server is not available.",
                 "InstallProtocolDoc": "To open this document you must install a custom protocol.",
                 "InstallProtocolDocDownload": "Download and install the file below:",
                 "InstallProtocolDocOtherOS": "Other OS",
                 "InstallProtocolDocTitle": "Protocol Installation",
                 "InstallProtocolFm": "To open OS file manager you must install a custom protocol.",
                 "Item": "Item",
                 "ItemType": "Item type:",
                 "LocalResource": "Local Resource",
                 "Location": "Location:",
                 "Log": "Log",
                 "ManageProperties": "Manage Properties",
                 "Message": "Message",
                 "Modified": "Modified:",
                 "MoveFolderToSubfolderRestriction": "The destination folder is a subfolder of the source folder.",
                 "MoveFileToSameDirectoryRestriction": "The source and destination file names are the same.",
                 "Name": "Name",
                 "Namespace": "Namespace",
                 "NewFolder": "New Folder",
                 "NewFolderPattern": "New Folder",
                 "NewName": "New name",
                 "No": "No",
                 "NonExistentLocation": "Location does not exist.",
                 "NonSupportedFileType": "Non-supported file type. To playback, download the file and use a 3rd party application.",
                 "NotFoundLocation": "Location &quot;{0}&quot; not found.",
                 "NoToAll": "No to All",
                 "OK": "OK",
                 "OperationCannotBePerformed": "Operation Cannot Be Performed:",
                 "OverwriteConfirm": "Overwrite Confirm",
                 "Properties": "Properties",
                 "ProtectedForRunningFileExtension": "File with extension &quot;{0}&quot; protected for running.",
                 "PropertyNameRestriction": "Property name and namespace can not be empty and must begin with a letter, may be followed by letters, digits, hyphens, underscores and periods.",
                 "Rename": "Rename",
                 "RequestError": "Error",
                 "Safari51WindowsMultiUploadNotSupported": "Safari 5.1.x does not support multiselection via 'Browse' button. Please use drag and drop or select a single file only or use other web browser.",
                 "Search": "Search:",
                 "Size": "Size:",
                 "Source": "Source",
                 "SpecifyItemName": "Specify the item name",
                 "TargetFolder": "Target Folder",
                 "TotalSpace": "Total space:",
                 "Type": "Type",
                 "TrialPeriodExpired": "The trial period has expired.",
                 "UpdateFile": "Update File",
                 "Upload": "Upload",
                 "UploadCaption": "Upload",
                 "UploadCaptionForDnDFilesSupportedBrowsers": "To upload drag and drop files here or into folder structure.",
                 "UploadFile": "Upload Files",
                 "UploadInProgressWarning": "One or more files are being uploaded. If you close this page upload will be paused.",
                 "UsedPercent": "Used: {0}%",
                 "UsedSpace": "Used space:",
                 "Value": "Value",
                 "Versions": "Versions",
                 "VersionUpdateToThisTooltip": "Update to this version",
                 "Yes": "Yes",
                 "YesToAll": "Yes to All",
                 "WarningOldVersion": "Ajax File Browser has detected that your IT Hit WebDAV server version is {0}. For correct versions support it is recommended to upgrade to v3.5.x or later version. To avoid this message set SuppressServerWarning=true when creating Ajax File Browser.",
                 "WebFoldersUpdate": "Please install <a target='_blank' href='{0}'>Software Update for Web Folders</a>."
             },
             "FileSizes": {
                 "Bytes": "Bytes",
                 "B": "B",
                 "GB": "GB",
                 "KB": "KB",
                 "MB": "MB"
             },
             "Menu": {
                 "ArrangeIconsBy": "Arrange Icons By",
                 "CancelUpload": "Cancel",
                 "Copy": "Copy",
                 "CustomProperties": "Custom Properties...",
                 "Cut": "Cut",
                 "Delete": "Delete",
                 "Details": "Details",
                 "EditDocument": "Edit Document",
                 "ExtraLargeIcons": "Extra Large Icons",
                 "LargeIcons": "Large Icons",
                 "Lock": "Lock...",
                 "Name": "Name",
                 "NewDocument": "New Document",
                 "NewFolder": "New Folder...",
                 "NewWord": "Microsoft Office Word Document",
                 "NewExcel": "Microsoft Office Excel Worksheet",
                 "NewPowerPoint": "Microsoft Office PowerPoint Presentation",
                 "MediumIcons": "Medium Icons",
                 "Modified": "Modified",
                 "OpenContainingFolderInFM": "Open Containing Folder",
                 "OpenDownload": "Download",
                 "OpenFolderInFM": "Open Folder in File Manager",
                 "OpenLocation": "Open Item Location",
                 "Paste": "Paste",
                 "PauseUpload": "Pause",
                 "Properties": "Properties...",
                 "Refresh": "Refresh",
                 "Rename": "Rename...",
                 "RestartUpload": "Restart Upload",
                 "ResumeUpload": "Resume",
                 "Size": "Size",
                 "Type": "Type",
                 "Unlock": "Unlock...",
                 "UpdateFile": "Update File...",
                 "UploadFile": "Upload Files...",
                 "UploadFolder": "Upload Folder...",
                 "Versions": "Versions...",
                 "View": "View",
                 "ViewError": "View Error..."
             },
             "Grid": {
                 "DateModified": "Date Modified",
                 "FileTypePrefix": "File ",
                 "Name": "Name",
                 "Size": "Size",
                 "Type": "Type",
                 "Folder": "Folder"
             },
             "Property": {
                 "Name": "Name",
                 "Namespace": "Namespace",
                 "Value": "Value"
             },
             "Version": {
                 "Name": "Version Name",
                 "CreationDate": "Creation Date",
                 "Size": "Size",
                 "Comments": "Comments",
                 "SavedBy": "Saved By"
             },
             "Upload": {
                 "Destination": "Destination",
                 "Elapsed": "Elapsed",
                 "Error": "Error",
                 "FileSize": "File Size",
                 "Left": "Left",
                 "Paused": "Paused",
                 "Progress": "Progress",
                 "ProgressPercent": "Status",
                 "Queued": "Queued",
                 "RetryIn": "Retry in {0}s",
                 "Source": "File",
                 "Speed": "Speed",
                 "Uploaded": "Uploaded"
             },
             "StatusDescriptions": {},
             "Exceptions": {
                 "TrySearchByResource": "You try to search by resource. Only folders support search.",
                 "BytesUploadedIsMoreThanTotalFileContentLength": "Bytes uploaded cannot be more than total file content length.",
                 "DestinationLocationNotPassed": "Destination URL is not passed.",
                 "EmptyElementParameter": "Element parameter is empty.",
                 "EmptyUrlProvided": "Please specify WebDAV server url.",
                 "FolderInstanceExpected": "ITHit.WebDAV.Client.AjaxFileBrowser.Folder instance object expected as input parameter.",
                 "FunctionalityNotSupported": "Functionality {0} is not supported by your browser.",
                 "HierarchyItemInstanceExpected": "ITHit.WebDAV.Client.AjaxFileBrowser.HierarchyItem instance object expected as input parameter.",
                 "InterfaceLabelIsNotPassed": "Interface label is not passed.",
                 "KeyCodeNotSpecified": "Key code not specified. Passed: {0}",
                 "NonExistentLocation": "Location &quot;{0}&quot; does not exist.",
                 "ResourceInstanceExpected": "ITHit.WebDAV.Client.AjaxFileBrowser.Resource instance object expected as input parameter.",
                 "SessionNotStarted": "Session is not started. Possible reason: ITHit WebDAV AJAX Library is not loaded.",
                 "UnexpectedUploadItemState": "Unexpected upload item state: {0}",
                 "UploadProgressInfoInstanceExpected": "ITHit.WebDAV.Client.AjaxFileBrowser.InternalUploadProgressInfo instance expected.",
                 "WrongBaseUrl": "Incorrect URL provided or URl is empty.",
                 "WrongContentLengthType": "File content length is expected to be an integer.",
                 "WrongCountAsMaximumUploadTasks": "Expected integer value above zero as count of maximum upload tasks at the same time. Passed: {0}",
                 "WrongCountInputParameters": "Wrong count of imput parameters passed.",
                 "WrongElementIdOrObject": "Expected element as string id or object.",
                 "WrongInterfaceHandler": "Wrong interface handler indentifier. Passed: {0}",
                 "WrongMenuItemType": "Passed wrong menu item type. Passed: {0}",
                 "WrongParametrType": "Wrong parameter type.",
                 "WrongTemplateIndex": "Passed wrong template index.",
                 "WrongUploadedBytesType": "Count of uploaded bytes expected to be a integer.",
                 "WrongUrl": "Passed wrong URL: &quot;{0}&quot;.",
                 "WrongViewModeIndex": "Passed wrong view mode index: &quot;{0}&quot;."
             },
             "ContextHelp": {
                 "Commands": {
                     "CancelUpload": "Cancel upload of the selected file.",
                     "Copy": "Copy the selected items to the clipboard. To put them in the new location, use the Paste command.",
                     "CustomProp": "Manage custom properties associated with the selected item.",
                     "Cut": "Cut the selected items to buffer.",
                     "Delete": "Deletes the selected items.",
                     "Download": "Download the selected file.",
                     "Edit": "Edit the selected file. Open document directly from server for editing with associated application.",
                     "FileManager": "Open this folder in Operating System's file manager.",
                     "Folders": "Show or hide navigation tree.",
                     "Info": "Show information about the selected item.",
                     "Lock": "Lock the selected file. The item will be protected from modification. Note that you would not be able to edit the file as well.",
                     "Log": "Show log. Send this log to administrator if you experience any issues, togather with a description and screenshots.",
                     "NewDocument": "Create a new Microsoft Office document.",
                     "NewExcel": "Create a new Microsoft Office Excel document.",
                     "NewFolder": "Create a new folder",
                     "NewPowerPoint": "Creates a new Microsoft Office PowerPoint document.",
                     "NewWord": "Creates new Microsoft Office Word document.",
                     "OpenLocation": "Navigate to folder that contains this file.",
                     "Paste": "Paste the content of the buffer to the current location.",
                     "PauseUpload": "Pause upload of the selected file(s).",
                     "RedoButton": "Redo undone operation.",
                     "Refresh": "Refresh content of this folder.",
                     "Rename": "Rename the selected item.",
                     "RestartUpload": "Restart file upload.",
                     "ResumeUpload": "Resume upload of the selected file(s).",
                     "Undo": "Undo previous operation.",
                     "Unlock": "Unlock item.",
                     "Up": "Navigate one level up in the folder structure.",
                     "UpdateFile": "Update file content. Your file will be overwritten with a selected file.",
                     "Upload": "Upload files to selected folder.",
                     "UploadFolder": "Upload local folder with all contained files to selected folder.",
                     "Versions": "Manage file versions. Download previous file versions, delete and rollback to previous versions.",
                     "Views": "Displays items using thumbnails or details view.",
                     "ViewsDetails": "Displays items using details view.",
                     "ViewsMedium": "Displays items using medium view.",
                     "ViewsLarge": "Displays items using large view.",
                     "ViewsExtraLarge": "Displays items using extra large view.",
                     "ViewError": "Show upload errors.",
                     "Eject": "Safely eject your micro SD or USB drive before removing it from the mobile router.",
                     "Play": "Playback media file. For non-supported types, download the file and use a 3rd party application."
                 }
             }
         },
         "Exceptions": {
             "ObjectExpected": "Object or null expected.",
             "UndefinedEventHandler": "Event handler {0}::{1} is undefined."
         }
     };

 	function nameToId(name) {
		return name.replace(/\./g,'_').toLowerCase();
	};
	/**
	 * @param {string} stringId
	 * @param {Object=} parts
	 */
	function _get(stringId,parts) {
		var retString;
		if(strings.hasOwnProperty(stringId)) {
			retString = strings[stringId];	
			for(var key in parts) {
				if(parts.hasOwnProperty(key)) {
					retString = retString.replace('${', '{').split('{' + key + '}').join(parts[key]);
				}
			}
		}
		else {
			if(typeof window.console !== 'undefined') {
				//window.console.log("FIXME: searched for missing string: " + stringId);
			}
		
			//retString = "FIXME: MISSING STRING + " + stringId;
			retString = stringId;
		}
		
		return retString;
	};
	
	function _getLabel(labelId){
		return _get('label_' + labelId);
	};
	
	function _getFieldLabel(fieldIdentifier) {
		return _getLabel(nameToId(fieldIdentifier));
	};
	
	function _getOptionLabel(fieldIdentifier, value) {
		return _get('option_' + nameToId(fieldIdentifier) + '-' + value);	
	};

	this.phrases = _phrases,
	this.get = _get,
	this.getLabel = _getLabel,
	this.getFieldLabel = _getFieldLabel,
	this.getOptionLabel = _getOptionLabel;
};
